## Illustrating a change of basis

In [1]:
import numpy as np

# 2-D Example

In [2]:
# This is the standard basis, (column) vectors (1,0) and (0,1)
basis1 = np.eye(2)
basis1

array([[ 1.,  0.],
       [ 0.,  1.]])

In [3]:
# This is an alternative basis, column vectors (1,3) and (1,-1)
basis2 = np.array([[1,1],[3,-1]])
basis2

array([[ 1,  1],
       [ 3, -1]])

In [4]:
# Consider the vector (3,1).  I could represent it two ways:
# In the first basis it is 3 times the col vector(1,0) + 1 times the column vector (0,1)
# In the second basis I could write it as 1 times (1,3) + 2 times (1,-1)

vector_in_basis1 = 1*basis2[:,0] + 2*basis2[:,1]
vector_in_basis1

array([3, 1])

So the vector (3,1) in our *standard* basis {(1,0),(0,1)} can also be represented as (1,2) in our alternate basis {(1,3),(-1,1)}


This is similar to how we represent numbers in binary vs decimal (or hexadecimal).  The number 21 (in decimal) would be represented as 1101 in binary or 15 in hexadecimal.

In [5]:
vector_in_basis2 = np.array([1,2])
vector_in_basis2

array([1, 2])

In [6]:
basis2inv = np.linalg.inv(basis2)
basis2inv

array([[ 0.25,  0.25],
       [ 0.75, -0.25]])

In [7]:
np.dot(basis2inv,vector_in_basis1)

array([ 1.,  2.])

In [8]:
np.dot(basis2,vector_in_basis2)

array([3, 1])

## 3D Example

In [9]:
bas1 = np.eye(3)

In [10]:
vec1 = 5 * bas1[:,0] + 2*bas1[:,1] + 12*bas1[:,2]
vec1

array([  5.,   2.,  12.])

In [11]:
bas2 = np.array([[1, 2, 3],[2,4,2],[3,1,5]])
bas2

array([[1, 2, 3],
       [2, 4, 2],
       [3, 1, 5]])

In [12]:
vec2 = 1 * bas2[:,0] + (-1) * bas2[:,1] + 2 * bas2[:,2]
vec2

array([ 5,  2, 12])

This illustrates how I could represent the point (or vector) (5,2,12) in two different ways.  In our standard basis, we represent this as [5,2,12] but in basis 2, (where the basis vectors are (1,2,3), (2,4,1) and (3,2,5) we would represent it as [1,-1,2].


In [13]:
np.dot(bas2, np.array([1,-1,2]))

array([ 5,  2, 12])

In [14]:
np.linalg.inv(bas2)

array([[-0.9 ,  0.35,  0.4 ],
       [ 0.2 ,  0.2 , -0.2 ],
       [ 0.5 , -0.25,  0.  ]])

In [15]:
np.dot(np.linalg.inv(bas2),vec1)

array([ 1., -1.,  2.])

So what does this have to do with PCA?  The idea is that we want to change our basis in a way so that the first few components carry "most" of the "information" (variation).  We can then "project" our datapoints down to fewer dimensions.

In [16]:
eig_vals, Q = np.linalg.eig(bas2)

In [17]:
eig_vals

array([ 7.91062807, -0.8578421 ,  2.94721403])

In [18]:
Q

array([[-0.45982363, -0.88647067, -0.07238059],
       [-0.57935094,  0.19151406, -0.85091344],
       [-0.67298939,  0.42129813,  0.52029546]])

In [19]:
Q.dot(vec1)

array([ -4.94062658, -12.72468787,   3.72119481])