# Markov Chains, Page Rank and Eigenthings

A markov chain is for modeling systems that are
* Random
* Memoryless


Examples of systems that can be modelled with Markov Chains
* Traffic Flows
* Boardgames
* Protein Conformations
* Internet traffic
* Stock Market
* trust networks
* job transitions
* liquid democracy

In [5]:
import IPython
iframe = '<iframe src=http://setosa.io/markov/index.html#%7B%22tm%22%3A%5B%5B0.1%2C0.9%5D%2C%5B0.5%2C0.5%5D%5D%7D width=700 height=350></iframe>'
IPython.display.HTML(iframe)

In [6]:
iframe = '<iframe src=http://setosa.io/markov/index.html#%7B%22tm%22%3A%5B%5B0.1%2C0.8%2C0.1%5D%2C%5B0.5%2C0%2C0.5%5D%2C%5B0.6%2C0.2%2C0.2%5D%5D%7D width=700 height=350></iframe>'
IPython.display.HTML(iframe)


Markov Chains can be represented as matrices

We just need to make a transition matrix
$$\begin{bmatrix}.4 & .5\\.6 & .5\end{bmatrix}$$

each column needs to sum to 1 because they are probabilities
$$\begin{bmatrix}.4 & .5\\.6 & .5\end{bmatrix} \begin{bmatrix}1\\0\end{bmatrix} = \begin{bmatrix}.4\\.6\end{bmatrix}$$

or each row needs to sum to 1 and we premultiply
$$\begin{bmatrix}1\\0\end{bmatrix} \begin{bmatrix}.4 & .6\\.5 & .5\end{bmatrix}  = \begin{bmatrix}.4\\.6\end{bmatrix}$$

Choice is arbitrary, just be consistant

once we have defined a transition matrix, we can figure out the probability we will be in each state in **one** step
$$\begin{bmatrix}.4 & .5\\.6 & .5\end{bmatrix} \begin{bmatrix}1\\0\end{bmatrix} = \begin{bmatrix}.4\\.6\end{bmatrix}$$

In [81]:
import numpy as np
P = [[.4, .5], 
     [.6, .5]]
a = [[1], [0]]

np.dot(P, a)


array([[ 0.4],
       [ 0.6]])

in two steps

$$\begin{bmatrix}.4 & .5\\.6 & .5\end{bmatrix} \begin{bmatrix}.4 & .5\\.6 & .5\end{bmatrix} \begin{bmatrix}1\\0\end{bmatrix} = \begin{bmatrix}.46\\.54\end{bmatrix}$$

In [82]:
np.dot(np.dot(P, P),a)

array([[ 0.46],
       [ 0.54]])

In [83]:
def markov_process(n,P,x):
    a = np.identity(len(P))
    for i in range(n):
        a = np.dot(P,a)
    print("probability of each state after {} transitions: ".format(n))
    print(np.dot(a,x))

markov_process(3,P,a)

probability of each state after 3 transitions: 
[[ 0.454]
 [ 0.546]]


In [84]:
markov_process(4,P,a)

probability of each state after 4 transitions: 
[[ 0.4546]
 [ 0.5454]]


In [85]:
markov_process(10,P,a)

probability of each state after 10 transitions: 
[[ 0.45454545]
 [ 0.54545455]]


In [86]:
markov_process(100,P,a)

probability of each state after 100 transitions: 
[[ 0.45454545]
 [ 0.54545455]]


What is going on?
The probability is not changing

* We have converged on a steady state.

* This is an example of a markov chain with a stationary distrubution. 

* Most markov chains have a steady state as $n \to \infty $

* some don't ...

## Periodic Markov Chains

In [87]:
P = [[0, 1], 
     [1, 0]]
a = [[1], [0]]

markov_process(3,P,a)

probability of each state after 3 transitions: 
[[ 0.]
 [ 1.]]


In [88]:
markov_process(4,P,a)

probability of each state after 4 transitions: 
[[ 1.]
 [ 0.]]


In [89]:
markov_process(5,P,a)

probability of each state after 5 transitions: 
[[ 0.]
 [ 1.]]


In [90]:
markov_process(1000,P,a)

probability of each state after 1000 transitions: 
[[ 1.]
 [ 0.]]


In [91]:
markov_process(1001,P,a)

probability of each state after 1001 transitions: 
[[ 0.]
 [ 1.]]


Not converging, but has a periodic distrubution

In [92]:
iframe = '<iframe src=http://setosa.io/markov/index.html#%7B%22tm%22%3A%5B%5B0%2C1%5D%2C%5B1%2C0%5D%5D%7D width=700 height=350></iframe>'
IPython.display.HTML(iframe)

### What happens if you just tweak the periodic markov chain a tiny bit?

In [93]:
P = [[.001, .999], 
     [.999, .001]]
a = [[1], [0]]

markov_process(3,P,a)

probability of each state after 3 transitions: 
[[ 0.002994]
 [ 0.997006]]


In [94]:
markov_process(4,P,a)

probability of each state after 4 transitions: 
[[ 0.99601198]
 [ 0.00398802]]


In [95]:
markov_process(5,P,a)

probability of each state after 5 transitions: 
[[ 0.00498004]
 [ 0.99501996]]


In [96]:
markov_process(10,P,a)

probability of each state after 10 transitions: 
[[ 0.99008952]
 [ 0.00991048]]


In [97]:
markov_process(100,P,a)

probability of each state after 100 transitions: 
[[ 0.9092834]
 [ 0.0907166]]


In [98]:
markov_process(1000,P,a)

probability of each state after 1000 transitions: 
[[ 0.56753226]
 [ 0.43246774]]


# Absorbing Markov Chain

In [101]:

iframe = '<iframe src=http://setosa.io/markov/index.html#%7B%22tm%22%3A%5B%5B0.2%2C0.8%2C0%2C0%5D%2C%5B0.2%2C0.6%2C0.2%2C0%5D%2C%5B0%2C0.1%2C0.8%2C0.1%5D%2C%5B0%2C0%2C0%2C1%5D%5D%7D width=700 height=350></iframe>'
IPython.display.HTML(iframe)

In [102]:
P = [[0.2,0.2,  0,0],
    [0.8 ,0.6,0.1,0],
    [0   ,0.2,0.8,0],
    [0   ,0  ,0.1,1]]

a = [[1],[0],[0],[0]]

markov_process(3,P,a)

probability of each state after 3 transitions: 
[[ 0.168]
 [ 0.56 ]
 [ 0.256]
 [ 0.016]]


In [103]:
markov_process(10,P,a)

probability of each state after 10 transitions: 
[[ 0.08168589]
 [ 0.29968215]
 [ 0.36042186]
 [ 0.2582101 ]]


In [104]:
markov_process(100,P,a)

probability of each state after 100 transitions: 
[[  6.56531547e-04]
 [  2.45698097e-03]
 [  3.30966508e-03]
 [  9.93576822e-01]]


Eventually everything ends up stuck in a final state

* like the 'win' state in a boardgame

## Solving for the state at $\infty$

We have seen that we can approximate a solution for some networks that quickly converge.

But how do we actually find the state at infinite time?

We want to find an $\bar x$, such that after applying our transform $P$ $\bar x$ remains the same

$$P \bar x = \bar x$$

This is a special case of the Eigen Vector equation
$$P \bar x = \lambda \bar x$$
$$P \bar x = \lambda I\bar x$$
where $I=\begin{bmatrix}1 & 0\\0 & 1\end{bmatrix}$
$$P \bar x - \lambda I\bar x = \bar 0$$
$$(P - \lambda I)\bar x = \bar 0$$


$$Det(P−λI) = 0$$

## example time

$\lambda = 1$
for all non periodic transistion matrices!

So $$P \bar x = \bar x$$ will always have a solution!